// Auto-generated by tools/transpile-glsl.js from atmosphere-webgl.js.
// DO NOT EDIT BY HAND — re-run the transpiler after changing the GLSL source.

// ===== fragmentShader =====
// Three.js Transpiler r185

import { Discard, Fn, If, Loop, add, cameraProjectionMatrix, clamp, div, dot, exp, float, int, length, max, min, mix, modelViewMatrix, mul, normalize, positionLocal, pow, screenUV, smoothstep, sqrt, sub, texture, uniform, vec2, vec3, vec4 } from 'three/tsl';

export function createFragment(uniforms) {
  const { atmoColor, density, uGroundR, uAtmoR, tSceneDepth, uDepthReady, uCameraFar, uVolumeSize, sunDir, uCameraLocal } = uniforms;

// positionLocal is already a VaryingNode (positionGeometry.toVarying).
// Use it directly — wrapping in varying() creates a nested varying that
// fails to resolve 'position' in the vertex shader. screenUV replaces
// gl_FragCoord.xy/uVolumeSize (already-normalized 0-1 screen coordinates).
const vDirection = positionLocal.sub( uCameraLocal );
const vViewDirection = modelViewMatrix.mul( vec4( positionLocal, 1.0 ) ).xyz;

const sphereHits = /*@__PURE__*/ Fn( ( [ origin, r, dir ] ) => {

	const b = dot( origin, dir );
	const disc = b.mul( b ).sub( dot( origin, origin ) ).add( r.mul( r ) );

	If( disc.lessThan( 0.0 ), () => {

		return vec2( - 1.0 );

	} );

	const s = sqrt( disc );

	return vec2( b.negate().sub( s ), b.negate().add( s ) );

}, { origin: 'vec3', r: 'float', dir: 'vec3', return: 'vec2' } );

const sceneRayLimit = /*@__PURE__*/ Fn( ( [ uv, viewDir ] ) => {

	If( uDepthReady.lessThan( 0.5 ), () => {

		return 1e20;

	} );

	const depth = tSceneDepth.sample( clamp( uv, 0.0, 1.0 ) ).x;

	If( depth.greaterThanEqual( 0.999999 ), () => {

		return 1e20;

	} );

	const forwardDistance = pow( uCameraFar.add( 1.0 ), depth ).sub( 1.0 );
	const forwardCos = max( normalize( viewDir ).z.negate(), 0.035 );

	return forwardDistance.div( forwardCos );

}, { uv: 'vec2', viewDir: 'vec3', return: 'float' } );

const main = /*@__PURE__*/ Fn( () => {

	const dir = normalize( vDirection );
	const outer = sphereHits( uCameraLocal, uAtmoR, dir );

	If( outer.y.lessThanEqual( 0.0 ), () => {

		Discard();

	} );

	const ground = sphereHits( uCameraLocal, uGroundR, dir );
	const t0 = max( outer.x, 0.0 );
	const t1 = outer.y;

	If( ground.x.greaterThan( t0 ), () => {

		t1.assign( min( t1, ground.x ) );

	} );

	t1.assign( min( t1, sceneRayLimit( screenUV, vViewDirection ).add( 1.5 ) ) );

	If( t1.lessThanEqual( t0 ), () => {

		Discard();

	} );

	const STEPS = int( 14 );
	const dt = t1.sub( t0 ).div( float( STEPS ) );
	const t = t0.add( dt.mul( 0.5 ) );
	const mu = dot( dir, normalize( sunDir ) );
	const rayleighPhase = mul( 0.05968, add( 1.0, mu.mul( mu ) ) );
	const g = float( 0.76 );
	const miePhase = mul( 0.07958, sub( 1.0, g.mul( g ) ) ).div( pow( max( 0.04, add( 1.0, g.mul( g ) ).sub( mul( 2.0, g ).mul( mu ) ) ), 1.5 ) );
	const rayleighColor = mix( vec3( 0.48, 0.68, 1.0 ), max( atmoColor, vec3( 0.015 ) ), 0.58 );
	const col = vec3( 0.0 );
	const trans = float( 1.0 );

	Loop( { start: 0, end: STEPS }, ( { i } ) => {

		const p = uCameraLocal.add( dir.mul( t ) );
		const r = length( p );
		const h = clamp( r.sub( uGroundR ).div( max( uAtmoR.sub( uGroundR ), 1.0 ) ), 0.0, 1.0 );
		const rhoR = exp( h.negate().mul( 6.2 ) ).mul( density );
		const rhoM = exp( h.negate().mul( 15.0 ) ).mul( density ).mul( 0.22 );
		const radial = p.div( max( r, 1.0 ) );
		const sunMu = dot( radial, normalize( sunDir ) );
		const horizon = smoothstep( - 0.13, 0.055, sunMu );
		const slant = div( 1.0, max( 0.16, sunMu.add( 0.32 ) ) );
		const sunTrans = exp( rhoR.mul( 0.32 ).add( rhoM.mul( 1.4 ) ).negate().mul( slant ) ).mul( horizon );

		// Soft multi-scatter approximation keeps the terminator and cloud
		// shadows from turning unnaturally black while preserving sunset.

		const scatter = rayleighColor.mul( rhoR ).mul( rayleighPhase ).add( vec3( 1.0, 0.93, 0.82 ).mul( rhoM ).mul( miePhase ) );
		scatter.mulAssign( sunTrans.add( mul( 0.075, density ).mul( sub( 1.0, h ) ) ) );
		const extinction = rhoR.mul( 0.58 ).add( rhoM.mul( 1.8 ) ).mul( dt ).div( max( uAtmoR.sub( uGroundR ), 1.0 ) );
		const a = sub( 1.0, exp( extinction.negate().mul( 0.62 ) ) );
		col.addAssign( trans.mul( a ).mul( scatter ).mul( 11.0 ) );
		trans.mulAssign( sub( 1.0, a ) );
		t.addAssign( dt );

	} );

	const alpha = clamp( sub( 1.0, trans ), 0.0, 0.985 );

	If( alpha.lessThan( 0.001 ), () => {

		Discard();

	} );

	return  vec4( col, alpha ) ;

} );

  return main;
}


// ===== vertexShader =====
// Three.js Transpiler r185



export function createVertex(uniforms) {
  const { uCameraLocal } = uniforms;

// Varying values are set by the VaryingNode constructor in createFragment —
// the builder auto-generates the vertex-stage assignment. The vertex Fn only
// needs to return the clip-space position.
const main = /*@__PURE__*/ Fn( () => {

	const viewPosition = modelViewMatrix.mul( vec4( positionLocal, 1.0 ) );
	return  cameraProjectionMatrix.mul( viewPosition ) ;

}, { return: 'vec4' } );

  return main;
}

