// Auto-generated by tools/transpile-glsl.js from clouds-webgl.js.
// DO NOT EDIT BY HAND — re-run the transpiler after changing the GLSL source.

// ===== fragmentShader =====
// Three.js Transpiler r185

import { Break, Discard, Fn, If, Loop, abs, add, cameraProjectionMatrix, clamp, cos, cross, div, dot, exp, float, fract, int, length, max, min, mix, mod, modelViewMatrix, mul, normalize, positionLocal, pow, screenUV, select, sin, smoothstep, sqrt, sub, texture, texture3D, uniform, vec2, vec3, vec4 } from 'three/tsl';

export function createFragment(uniforms) {
  const { uNoise3, uCloudNoise, tSceneDepth, uCov0, uCov1, uRin, uRout, uGroundR, uEngage, uFrame, uQuality, uDepthReady, uCameraFar, uVolumeSize, uCOff, uStormA, uStormB, uCameraLocal, uSunDir, uSunC, uAmbC, uTint, uSpin } = uniforms;

// positionLocal is already a VaryingNode (positionGeometry.toVarying).
// Use it directly — wrapping in varying() creates a nested varying that
// fails to resolve 'position' in the vertex shader. screenUV replaces
// gl_FragCoord.xy/uVolumeSize (already-normalized 0-1 screen coordinates).
const vDirection = positionLocal.sub( uCameraLocal );
const vViewDirection = modelViewMatrix.mul( vec4( positionLocal, 1.0 ) ).xyz;

// the SAME coverage fbm the impostor deck, terrain shadows and the CPU
// transit fog use — one sky, everywhere. Explicit LOD: implicit
// derivatives are UNDEFINED in the divergent march loop and flicker.

const cloudFbm = /*@__PURE__*/ Fn( ( [ d ] ) => {

	const f = uCloudNoise.sample( d.xy.mul( 0.55 ).add( uCOff.xy ) ).level( 0.0 ).g.mul( 0.5 );
	f.addAssign( uCloudNoise.sample( d.yz.mul( 1.15 ).add( uCOff.yz ) ).level( 0.0 ).r.mul( 0.25 ) );
	f.addAssign( uCloudNoise.sample( d.zx.mul( 2.35 ).add( uCOff.zx ) ).level( 0.0 ).g.mul( 0.125 ) );
	f.addAssign( uCloudNoise.sample( d.xy.mul( 4.8 ).sub( uCOff.xz ) ).level( 0.0 ).r.mul( 0.0625 ) );

	return f.div( 0.9375 );

}, { d: 'vec3', return: 'float' } );

const stormAt = /*@__PURE__*/ Fn( ( [ d, center, phase, radius ] ) => {

	const ref = select( abs( center.y ).lessThan( 0.88 ), vec3( 0.0, 1.0, 0.0 ), vec3( 1.0, 0.0, 0.0 ) );
	const ta = normalize( cross( ref, center ) );
	const tb = normalize( cross( center, ta ) );
	const z = clamp( dot( d, center ), - 1.0, 1.0 );
	const x = dot( d, ta ), y = dot( d, tb );
	const inv = div( 1.0, max( x.mul( x ).add( y.mul( y ) ), 1e-5 ) );
	const sin2 = mul( 2.0, x ).mul( y ).mul( inv );
	const cos2 = x.mul( x ).sub( y.mul( y ) ).mul( inv );
	const r = sqrt( max( 0.0, mul( 2.0, sub( 1.0, z ) ) ) ).div( radius );
	const shield = sub( 1.0, smoothstep( 0.08, 0.5, r ) ).mul( 0.58 );
	const turn = phase.sub( r.mul( 13.0 ) );
	const arms = smoothstep( 0.66, 0.94, add( 0.5, mul( 0.5, sin2.mul( cos( turn ) ).add( cos2.mul( sin( turn ) ) ) ) ) );
	arms.mulAssign( smoothstep( 0.1, 0.24, r ).mul( sub( 1.0, smoothstep( 0.62, 1.0, r ) ) ) );

	return max( shield, arms );

}, { d: 'vec3', center: 'vec3', phase: 'float', radius: 'float', return: 'float' } );

const weatherSystem = /*@__PURE__*/ Fn( ( [ d ] ) => {

	return max( stormAt( d, uStormA, uCOff.z, 0.92 ), stormAt( d, uStormB, uCOff.x.add( uCOff.y ), 0.68 ).mul( 0.72 ) );

}, { d: 'vec3', return: 'float' } );

const sphereHits = /*@__PURE__*/ Fn( ( [ origin, r, dir ] ) => {

	const b = dot( origin, dir );
	const disc = b.mul( b ).sub( dot( origin, origin ) ).add( r.mul( r ) );

	If( disc.lessThan( 0.0 ), () => {

		return vec2( - 1.0 );

	} );

	const s = sqrt( disc );

	return vec2( b.negate().sub( s ), b.negate().add( s ) );

}, { origin: 'vec3', r: 'float', dir: 'vec3', return: 'vec2' } );

const sceneRayLimit = /*@__PURE__*/ Fn( ( [ uv, viewDir ] ) => {

	If( uDepthReady.lessThan( 0.5 ), () => {

		return 1e20;

	} );

	const depth = tSceneDepth.sample( clamp( uv, 0.0, 1.0 ) ).x;

	If( depth.greaterThanEqual( 0.999999 ), () => {

		return 1e20;

	} );

	// Three.js logarithmic depth: depth = log2(1 + clipW)/log2(1 + far).

	const forwardDistance = pow( uCameraFar.add( 1.0 ), depth ).sub( 1.0 );
	const forwardCos = max( normalize( viewDir ).z.negate(), 0.035 );

	return forwardDistance.div( forwardCos );

}, { uv: 'vec2', viewDir: 'vec3', return: 'float' } );

const densityAt = /*@__PURE__*/ Fn( ( [ local, covScale, systemMask ] ) => {

	const r = length( local );
	const h = clamp( r.sub( uRin ).div( uRout.sub( uRin ) ), 0.0, 1.0 );
	const radial = local.div( r );
	const tangentA = normalize( cross( radial, select( abs( radial.y ).lessThan( 0.88 ), vec3( 0.0, 1.0, 0.0 ), vec3( 1.0, 0.0, 0.0 ) ) ) );
	const tangentB = normalize( cross( radial, tangentA ) );
	const bend = h.sub( 0.42 );

	// A cloud footprint must not be the same 2D mask extruded straight
	// through the whole shell. Shift it laterally with altitude so anvils,
	// shelves and tilted billows replace the former vertical curtains.

	const coverageDir = normalize( radial.add( tangentA.mul( bend ).mul( 0.02 ) ).add( tangentB.mul( bend.mul( bend ).sub( 0.08 ) ).mul( 0.015 ) ) );
	const sd = uSpin.mul( coverageDir );
	const fine = cloudFbm( sd );

	// Preserve the complete analytic weather footprint. Earlier the
	// volume raised this mask to 1.42 and then gated it again with Worley,
	// deleting most clouds that were visible in the orbit deck.

	const baseWeather = pow( smoothstep( uCov0, uCov1, fine ), 0.92 );
	const largeSystem = systemMask.mul( smoothstep( 0.24, 0.68, fine ) ).mul( 0.86 );
	const cov = max( baseWeather, largeSystem ).mul( covScale );

	If( cov.lessThan( 0.01 ), () => {

		return 0.0;

	} );

	const warp = vec3( uCloudNoise.sample( sd.yz.mul( 3.1 ).add( uCOff.xy ) ).level( 0.0 ).r, uCloudNoise.sample( sd.zx.mul( 3.7 ).add( uCOff.yz ) ).level( 0.0 ).g, uCloudNoise.sample( sd.xy.mul( 4.3 ).sub( uCOff.xz ) ).level( 0.0 ).r ).sub( 0.5 );

	// Sample the base volume in a spherical weather frame: horizontal
	// scale follows the planet surface while height travels through a
	// separate oblique noise axis. Sampling raw world metres here made
	// ray steps line up into long radial brush strokes.
	// Planet-scale billows first; fine Worley erosion is added below.
	// Using a fixed 26 km cell size repeated identical popcorn all around
	// a large world and closed into a bright ring at the limb.

	const q = uSpin.mul( radial ).mul( uRin.div( 118000.0 ) ).add( vec3( 0.37, 0.71, 0.53 ).mul( h.mul( 2.7 ) ) ).add( warp.mul( 1.4 ) );
	const n = uNoise3.sample( q ).level( 0.8 ).rg;

	// Locally varied floor and ceiling prevent a single hard lower edge.

	const floorH = add( 0.025, sub( 1.0, n.g ).mul( 0.13 ) );
	const ceilH = add( 0.44, cov.mul( 0.34 ) ).add( n.r.sub( 0.5 ).mul( 0.18 ) );
	const lowerProfile = smoothstep( floorH, floorH.add( 0.14 ), h ).mul( sub( 1.0, smoothstep( ceilH.sub( 0.18 ), ceilH, h ) ) );

	// Deep weather systems build a distinct, broad upper shelf. It shares
	// the same footprint and 3D field as the lower cloud, but a displaced
	// vertical profile creates towers, anvils and gaps instead of one
	// uniformly extruded layer.

	const upperNoise = uNoise3.sample( q.mul( 1.72 ).add( vec3( 5.7, 2.3, 8.1 ) ) ).level( 1.15 ).rg;
	const upperSource = smoothstep( 0.28, 0.76, systemMask ).mul( smoothstep( 0.26, 0.74, cov ) );
	const upperFloor = add( 0.48, upperNoise.g.sub( 0.5 ).mul( 0.12 ) );
	const upperCeil = add( 0.91, upperNoise.r.sub( 0.5 ).mul( 0.10 ) );
	const upperProfile = smoothstep( upperFloor, upperFloor.add( 0.11 ), h ).mul( sub( 1.0, smoothstep( upperCeil.sub( 0.11 ), upperCeil, h ) ) );

	// Sparse high-altitude filaments soften storm tops without inventing
	// a second camera-facing weather map.

	const wisp = smoothstep( 0.58, 0.88, upperNoise.g ).mul( smoothstep( 0.62, 0.73, h ) ).mul( sub( 1.0, smoothstep( 0.91, 0.99, h ) ) );

	// 3D noise shapes density inside the footprint; it must not decide
	// whether the footprint exists. A non-zero floor gives broad cloud
	// bodies real depth while Worley still sculpts billowing edges.

	const cells = mix( 0.58, 1.22, smoothstep( 0.18, 0.82, n.r ) );
	const verticalShape = max( lowerProfile.mul( cells ), upperSource.mul( upperProfile ).mul( add( 0.54, upperNoise.r.mul( 0.52 ) ) ) );
	verticalShape.assign( max( verticalShape, upperSource.mul( wisp ).mul( 0.34 ) ) );
	const d = cov.mul( verticalShape );
	const ero = uNoise3.sample( q.mul( 3.15 ) ).level( 1.25 ).g;
	d.assign( clamp( d.sub( sub( 1.0, ero ).mul( 0.10 ).mul( sub( 1.0, d ) ) ), 0.0, 1.0 ) );

	return smoothstep( 0.018, 0.46, d );

}, { local: 'vec3', covScale: 'float', systemMask: 'float', return: 'float' } );

const hash12 = /*@__PURE__*/ Fn( ( [ p ] ) => {

	const p3 = fract( vec3( p.xyx ).mul( 0.1031 ) );
	p3.addAssign( dot( p3, p3.yzx.add( 33.33 ) ) );

	return fract( p3.x.add( p3.y ).mul( p3.z ) );

}, { p: 'vec2', return: 'float' } );

const main = /*@__PURE__*/ Fn( () => {

	If( uEngage.lessThan( 0.01 ), () => {

		Discard();

	} );

	const dir = normalize( vDirection );
	const outer = sphereHits( uCameraLocal, uRout, dir );

	If( outer.y.lessThanEqual( 0.0 ), () => {

		Discard();

	} );

	const inner = sphereHits( uCameraLocal, uRin, dir );

	// march the FIRST pass through the shell only (the re-entry segment
	// on the far side is behind the planet for any ray that matters)

	const t0 = max( outer.x, 0.0 );
	const t1 = select( inner.x.greaterThan( 0.0 ), inner.x, outer.y );
	const camR = length( uCameraLocal );

	If( camR.lessThan( uRin ).and( inner.y.greaterThan( 0.0 ) ), () => {

		t0.assign( max( inner.y, 0.0 ) );
		t1.assign( outer.y );

	} );

	// From below the cloud base, rays aimed into the planet reach terrain
	// before reaching any cloud. Without this occlusion test the far-side
	// shell was integrated over the foreground and looked like a full-
	// screen cloud card.

	const ground = sphereHits( uCameraLocal, uGroundR, dir );

	If( ground.x.greaterThan( 0.0 ), () => {

		If( ground.x.lessThanEqual( t0 ), () => {

			Discard();

		} );

		t1.assign( min( t1, ground.x ) );

	} );

	// Stop the ray at the first opaque scene surface. Trees, rocks,
	// terrain and the ship now occlude the volume instead of receiving a
	// half-resolution cloud layer over their silhouettes.

	t1.assign( min( t1, sceneRayLimit( screenUV, vViewDirection ).add( 1.5 ) ) );
	t1.assign( min( t1, t0.add( uRout.sub( uRin ).mul( 6.5 ) ) ) );

	// grazing rays: bounded cost

	If( t1.lessThanEqual( t0 ), () => {

		Discard();

	} );

	const seg = t1.sub( t0 );
	const thick = uRout.sub( uRin );

	// This material is rendered by the half-resolution temporal volume
	// pass. A fresh jittered 44–84 sample signal reconstructs more cleanly
	// than 120 static steps and avoids the old grazing-angle brush tails.

	const minSteps = mix( 28.0, 46.0, uQuality );
	const maxSteps = mix( 52.0, 88.0, uQuality );
	const STEPS = int( clamp( seg.div( thick.mul( mix( 0.052, 0.032, uQuality ) ) ), minSteps, maxSteps ) );
	const dt = seg.div( float( STEPS ) );
	const framePhase = mod( uFrame, 16.0 );
	const jitter = hash12( screenUV.mul( max( uVolumeSize, vec2( 1.0 ) ) ).add( vec2( framePhase.mul( 19.19 ), framePhase.mul( 7.73 ) ) ) );
	const t = t0.add( dt.mul( jitter ) );

	// A weather system spans hundreds of kilometres while this shell is
	// only kilometres thick. Evaluate its footprint once per pixel; the
	// 3D billows, erosion and vertical profile still vary at every step.

	const systemDir = uSpin.mul( normalize( uCameraLocal.add( dir.mul( t0.add( t1 ).mul( 0.5 ) ) ) ) );
	const systemMask = weatherSystem( systemDir );
	const sigma = div( 6.4, thick );

	// extinction scale

	const mu = dot( dir, uSunDir );
	const hg = div( 1.0 - 0.28, mul( 12.566, pow( sub( 1.0 + 0.28, mul( 1.06, mu ) ), 1.5 ) ) );
	const back = div( 1.0 - 0.16, mul( 12.566, pow( add( 1.0 + 0.16, mul( 0.8, mu ) ), 1.5 ) ) );
	const phase = mix( 0.0796, hg.mul( 3.35 ).add( back.mul( 0.5 ) ), 0.76 );
	const col = vec3( 0.0 );
	const T = float( 1.0 );

	Loop( { start: 0, end: 124 }, ( { i } ) => {

		If( i.greaterThanEqual( STEPS ).or( T.lessThan( 0.02 ) ), () => {

			Break();

		} );

		const local = uCameraLocal.add( dir.mul( t ) );
		const d = densityAt( local, 1.0, systemMask );

		If( d.greaterThan( 0.003 ), () => {

			// short sun march: how buried is this sample?

			const od = float( 0.0 );
			const ls = thick.mul( 0.35 );
			od.addAssign( densityAt( local.add( uSunDir.mul( ls ).mul( 0.6 ) ), 1.0, systemMask ).mul( ls ).mul( 0.6 ) );
			od.addAssign( densityAt( local.add( uSunDir.mul( ls ).mul( 1.5 ) ), 1.0, systemMask ).mul( ls ).mul( 0.9 ) );

			If( uQuality.greaterThan( 0.5 ), () => {

				od.addAssign( densityAt( local.add( uSunDir.mul( ls ).mul( 2.8 ) ), 1.0, systemMask ).mul( ls ).mul( 1.3 ) );

			} ).Else( () => {

				// Preserve approximately the same optical depth with one fewer
				// lookup on the low tier, so the silhouette and coverage stay
				// stable while only fine self-shadow detail is reduced.

				od.mulAssign( 1.18 );

			} );

			const Tsun = exp( od.negate().mul( sigma ).mul( 0.9 ) );
			const powder = sub( 1.0, exp( d.negate().mul( sigma ).mul( dt ).mul( 2.0 ) ) );
			const hFrac = clamp( length( local ).sub( uRin ).div( thick ), 0.0, 1.0 );
			const silver = pow( Tsun, 2.4 ).mul( pow( max( mu, 0.0 ), 3.0 ) ).mul( sub( 1.0, smoothstep( 0.56, 0.96, d ) ) );
			const s = uSunC.mul( Tsun.mul( phase ).mul( 13.2 ).add( silver.mul( 0.82 ) ) ).add( uAmbC.mul( add( 0.42, mul( 0.62, hFrac ) ) ).mul( add( 0.72, Tsun.mul( 0.28 ) ) ) );
			const a = sub( 1.0, exp( d.negate().mul( sigma ).mul( dt ) ) );
			col.addAssign( T.mul( a ).mul( s ).mul( powder ).mul( uTint ) );
			T.mulAssign( sub( 1.0, a ) );

		} );

		t.addAssign( dt );

	} );

	const alpha = sub( 1.0, T ).mul( uEngage );

	If( alpha.lessThan( 0.004 ), () => {

		Discard();

	} );

	// RGB is already front-to-back integrated (premultiplied).

	return  vec4( col.mul( uEngage ), alpha ) ;

} );

  return main;
}


// ===== vertexShader =====
// Three.js Transpiler r185



export function createVertex(uniforms) {
  const { uCameraLocal } = uniforms;

// Varying values are set by the VaryingNode constructor in createFragment —
// the builder auto-generates the vertex-stage assignment. The vertex Fn only
// needs to return the clip-space position.
const main = /*@__PURE__*/ Fn( () => {

	const viewPosition = modelViewMatrix.mul( vec4( positionLocal, 1.0 ) );
	return  cameraProjectionMatrix.mul( viewPosition ) ;

}, { return: 'vec4' } );

  return main;
}

